[package]
name = "nixup"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
clap = "~2.32.0"
colored = "~1.7.0"
dirs = "~1.0.0"
failure = "~0.1.0"
regex = "~1.1.0"
lazy_static = "~1.2.0"
rmp-serde = "~0.13.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"

[profile.release]
lto = true
codegen-units = 1

[features]
no_colors = ["colored/no-color"]