[package]
name = "nixup"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
clap = "~2.33.0"
colored = "~1.8.0"
dirs = "~2.0.0"
failure = "~0.1.0"
libc = "~0.2.0"
rayon = "~1.0.0"
rmp-serde = "~0.13.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
smallvec = "~0.6.0"

[dependencies.hashbrown]
version = "~0.1.0"
features = ["serde", "rayon"]

[profile.release]
lto = true
codegen-units = 1

[features]
no_colors = ["colored/no-color"]