[package]
name = "nixup"
version = "0.0.0"
authors = [ "Acizza <jgit@tuta.io>" ]
edition = "2018"

[dependencies]
colored = "~1.8.0"
dirs = "~2.0.0"
rayon = "~1.2.0"
rmp-serde = "~0.13.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
smallvec = "~0.6.0"
snafu = "~0.5.0"

[dependencies.clap]
version = "~2.33.0"
default-features = false
features = [ "vec_map" ]

[profile.release]
lto = true
codegen-units = 1

[features]
no_colors = [ "colored/no-color" ]